In [21]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from pathlib import Path

import plotly.io as pio

In [2]:
DATA_PATH = Path("../data/processed/new_processed")

fund_master = pd.read_csv(DATA_PATH/"clean_fund_master.csv")
nav = pd.read_csv(DATA_PATH/"clean_nav_history.csv")
aum = pd.read_csv(DATA_PATH/"clean_aum.csv")
sip = pd.read_csv(DATA_PATH/"clean_sip.csv")
category = pd.read_csv(DATA_PATH/"clean_category.csv")
folio = pd.read_csv(DATA_PATH/"clean_folio.csv")
transactions = pd.read_csv(DATA_PATH/"clean_transactions.csv")
holdings = pd.read_csv(DATA_PATH/"clean_holdings.csv")

In [3]:
datasets = {
    "Fund Master": fund_master,
    "NAV": nav,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Transactions": transactions,
    "Holdings": holdings
}

for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.shape)
    display(df.head())

============================================================
Fund Master
(40, 15)

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
NAV
(46000, 3)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

============================================================
AUM
(90, 5)

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
SIP
(48, 6)

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,0.0
1,2022-02,11438,4.93,8.20,4.85,0.0
2,2022-03,12328,5.09,10.50,5.01,0.0
3,2022-04,11863,5.48,9.52,5.12,0.0
4,2022-05,12286,5.55,8.10,5.15,0.0

============================================================
Category
(144, 3)

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
Folio
(21, 6)

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

============================================================
Transactions
(32778, 13)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
Holdings
(322, 8)

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [26]:
nav["date"] = pd.to_datetime(nav["date"])

top_funds = nav["amfi_code"].unique()[:10]

nav_sample = nav[
    nav["amfi_code"].isin(top_funds)
]

fig = px.line(
    nav_sample,
    x="date",
    y="nav",
    color="amfi_code",
    title="NAV Trend Analysis (Top 10 Funds)"
)

fig.show()

In [5]:
top_aum = (
    aum.groupby("fund_house")["aum_crore"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

fig = px.bar(
    top_aum,
    x="aum_crore",
    y="fund_house",
    orientation="h",
    title="Top 10 Fund Houses by AUM",
    text_auto=True
)

fig.show()

In [6]:
sip["month"] = pd.to_datetime(sip["month"])

fig = px.line(
    sip,
    x="month",
    y="sip_inflow_crore",
    markers=True,
    title="Monthly SIP Inflow Trend"
)

fig.show()

In [7]:
pivot = category.pivot_table(
    values="net_inflow_crore",
    index="category",
    columns="month",
    aggfunc="sum"
)

fig = px.imshow(
    pivot,
    aspect="auto",
    title="Category-wise Inflow Heatmap"
)

fig.show()

In [8]:
age_data = (
    transactions["age_group"]
    .value_counts()
    .reset_index()
)

fig = px.pie(
    age_data,
    names="age_group",
    values="count",
    hole=0.5,
    title="Investor Age Distribution"
)

fig.show()

In [9]:
fig = px.box(
    transactions,
    x="age_group",
    y="amount_inr",
    color="age_group",
    title="Investment Amount by Age Group"
)

fig.show()

In [10]:
state_data = (
    transactions.groupby("state")
    ["amount_inr"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fig = px.bar(
    state_data,
    x="amount_inr",
    y="state",
    orientation="h",
    title="State-wise Investment Distribution"
)

fig.show()

In [11]:
tier_data = (
    transactions["city_tier"]
    .value_counts()
    .reset_index()
)

fig = px.pie(
    tier_data,
    names="city_tier",
    values="count",
    hole=0.5,
    title="T30 vs B30 Investor Distribution"
)

fig.show()

In [12]:
fig = px.line(
    folio,
    x=folio.columns[0],
    y=folio.columns[1],
    markers=True,
    title="Industry Folio Growth"
)

fig.show()

In [13]:
pivot_nav = nav.pivot_table(
    index="date",
    columns="amfi_code",
    values="nav"
)

returns = pivot_nav.pct_change()

corr = returns.corr()

fig = px.imshow(
    corr,
    title="Mutual Fund Correlation Matrix"
)

fig.show()

In [14]:
sector_data = (
    holdings.groupby("sector")
    ["weight_pct"]
    .sum()
    .reset_index()
)

fig = px.pie(
    sector_data,
    names="sector",
    values="weight_pct",
    hole=0.5,
    title="Sector Allocation"
)

fig.show()

In [15]:
top_states = (
    transactions.groupby("state")
    ["amount_inr"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_states)

state
Punjab            315780459
Tamil Nadu        315177237
Madhya Pradesh    308312493
Rajasthan         298645822
Gujarat           298358940
West Bengal       297182514
Telangana         290219284
Delhi             289633404
Uttar Pradesh     285368873
Haryana           279634354
Name: amount_inr, dtype: int64

In [16]:
top_funds = (
    transactions.groupby("amfi_code")
    ["amount_inr"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_funds)

amfi_code
102885    100374918
148568     99482585
119094     97384474
119095     96970660
119551     95041213
120506     93475766
101208     92931528
118636     92903919
102886     92430980
100025     92212042
Name: amount_inr, dtype: int64

In [17]:
for name, df in datasets.items():
    print("="*50)
    print(name)
    print(df.isnull().sum())

==================================================
Fund Master
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64
==================================================
NAV
amfi_code    0
date         0
nav          0
dtype: int64
==================================================
AUM
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64
==================================================
SIP
month                        0
sip_inflow_crore             0
active_sip_accounts_crore    0
new_sip_accounts_lakh        0
sip_aum_lakh_crore           0
yoy_growth_pct               0
dtype: int64
==================================================
Category
month               0
category            0
net_inflow_crore    0
dtype: int64
==================================================
Folio
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64
==================================================
Transactions
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64
==================================================
Holdings
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [18]:
print("""
1. Top AMC identified based on AUM.
2. SIP inflows show long-term growth trend.
3. Certain categories attract majority inflows.
4. Strong concentration of investors in T30 cities.
5. Few states dominate total investments.
6. Sector allocation heavily weighted toward key sectors.
7. Fund NAVs show positive long-term trends.
8. Correlation analysis identifies diversification opportunities.
9. Younger investors contribute significant SIP volume.
10. Top-performing funds attract highest transaction values.
""")

1. Top AMC identified based on AUM.
2. SIP inflows show long-term growth trend.
3. Certain categories attract majority inflows.
4. Strong concentration of investors in T30 cities.
5. Few states dominate total investments.
6. Sector allocation heavily weighted toward key sectors.
7. Fund NAVs show positive long-term trends.
8. Correlation analysis identifies diversification opportunities.
9. Younger investors contribute significant SIP volume.
10. Top-performing funds attract highest transaction values.